name:                sedhs
version:             0.1.0.0
github:              "topisani/sedhs"
license:             BSD3
author:              "Tobias Pisani"
maintainer:          "topisani@hamsterpoison.com"
copyright:           "2020 Tobias Pisani"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/topisani/sedhs#readme>

dependencies:
- base >= 4.7 && < 5
- tasty
- tasty-hunit
- mtl
- data-default

library:
  source-dirs: src

executables:
  sedhs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sedhs

tests:
  sedhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sedhs
